server:
  port: 8095
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.198.222
    username: wlkg
    password: 123456
    virtual-host: /wlkg
wlkg:
  sms:
    accessKeyId: LTAI4FeA8nveZPnf4fkD7RgT # 你自己的accessKeyId
    accessKeySecret: TUCk1QneBtsGmrAFaEhsoHU8VWwQsT # 你自己的AccessKeySecret
    signName: 窝里快商场 # 签名名称
    verifyCodeTemplate: SMS_177242911  # 模板名称