server:
  port: 8093
spring:
  main:
    allow-bean-definition-overriding: true  #多个接口上的@FeignClient(“相同服务名”)会报错，overriding is disabled。
  application:
    name: search-service
  jackson:
    default-property-inclusion:  non_null # 配置json处理时忽略空值
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.198.222:9300
  rabbitmq:
    host: 192.168.198.222
    username: wlkg
    password: 123456
    virtual-host: /wlkg
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}